"""Chef-grade method overrides for focus-kitchen dishes with one-line methods.

Keyed by exact recipe name. Used by parslia_spec.build_method.
"""

from __future__ import annotations

METHOD_OVERRIDES: dict[str, list[str]] = {
    "Hara bhara kebab (no onion garlic)": [
        "Mise en place. Weigh every item for 4 portions. Set a cast-iron tawa (not aluminium) and a stainless steel pot of salted water. Check garam masala and chaat masala contain no onion or garlic powder.",
        "Wash 2 cups spinach. Blanch in boiling water 45–60 seconds until wilted and bright. Shock in cold water. Squeeze very dry in a clean cloth — excess water makes kebabs collapse. Chop fine.",
        "Boil 2 medium potatoes (about 250 g) until a knife slips through, 12–15 minutes. Drain. Steam-dry 2 minutes. Peel and mash while warm, leaving a little texture.",
        "Boil or steam 1 cup green peas until tender, 4–5 minutes. Drain well. Lightly crush — do not puree to paste.",
        "Dry-roast 2 tbsp (16 g) besan in a steel kadai on low heat 3–4 minutes until the raw smell goes and the flour turns biscuit-coloured. Cool.",
        "In a steel bowl combine spinach, potato, peas, roasted besan, 20 g crushed ginger, 2 finely chopped green chillies, 1/2 tsp garam masala, 1/2 tsp chaat masala and 1 tsp salt. Mix until the mass holds when pressed. If wet, add 1 tbsp more roasted besan; if dry and cracking, sprinkle 1 tsp water.",
        "Rest 10 minutes. Divide into 12 portions of about 40 g. Shape into tikkis 1.5 cm thick with even edges so they brown evenly.",
        "Chill 15 minutes uncovered on a steel tray — this sets the starch and stops them breaking on the tawa.",
        "Heat the cast-iron tawa to medium. Add 1 tbsp ghee. When it shimmers, place kebabs without crowding. Cook 3–4 minutes until a deep green-brown crust forms. Flip once. Add remaining ghee as needed. Do not press hard or the filling squeezes out.",
        "Doneness: crust set, centre hot, no raw potato taste. Drain briefly on a steel rack.",
        "Serve hot, 3 kebabs per portion, with imli chutney or plain dahi. Label allergens before the pass.",
    ],
    "Paneer tikka (dahi-ajwain, no garlic)": [
        "Mise en place. Weigh 400 g paneer and 1 cup hung dahi. Set a cast-iron grill or steel oven tray — never aluminium foil. Confirm chilli powder and garam masala have no onion or garlic powder.",
        "Cut paneer into even 2.5 cm cubes. Pat very dry. Cut capsicum and tomato into similar squares so they cook in the same time.",
        "In a steel bowl whisk hung dahi with 1 tsp ajwain, 1 tsp Kashmiri chilli, turmeric, garam masala, salt and crushed ginger to a thick marinade that coats a spoon. No garlic paste.",
        "Fold paneer and vegetables through the marinade until every face is coated. Cover. Marinate 1 hour refrigerated (or 20 minutes at the pass if you are short of time).",
        "Thread onto steel skewers, alternating paneer and vegetable, leaving a little space between cubes so heat can circulate.",
        "Heat the cast-iron grill to medium-high until a drop of water dances. Brush with ghee. Lay skewers. Do not crowd.",
        "Grill 3–4 minutes per side until the dahi takes charred spots and the paneer is hot through. Turn with tongs. Brush once more with ghee.",
        "Doneness: edges blistered, centre hot, dahi set not wet. Rest 1 minute so juices settle.",
        "Finish with lemon juice at the pass. Serve 1 skewer per portion, hot. Hold no more than 10 minutes or the tikka steams and goes rubbery.",
    ],
    "Samosa (aloo-peas, no onion)": [
        "Mise en place. Weigh 3 cups maida, ghee, ajwain and filling vegetables. Set a steel kadhai for frying — never aluminium. Oil should be 6–8 cm deep.",
        "Rub ghee into maida with 1 tsp ajwain and salt until the mix looks like damp sand. Add water a spoon at a time to a firm dough. Rest covered 20 minutes.",
        "Boil 4 potatoes until tender. Drain, steam-dry, peel and mash coarsely. Blanch 1 cup peas 3 minutes. Drain.",
        "Heat ghee in a steel kadhai. Bloom cumin and a pinch of hing 20–30 seconds. Add potato, peas, chilli, coriander, amchur and salt. Cook 4–5 minutes until the filling is dry enough to hold a shape. Cool completely.",
        "Divide dough into 10 balls. Roll each to a 15 cm oval. Cut in half. Form a cone, seal the straight edge with water, fill 2 tbsp cooled filling, seal the mouth firmly. No air pockets.",
        "Heat oil to 170–175 C (a scrap of dough should rise in 8–10 seconds, not brown at once). Fry 4–5 samosas at a time.",
        "Fry 8–10 minutes, turning, until blistered and deep gold. If they brown in under 4 minutes the oil is too hot and the pastry stays raw.",
        "Doneness: pastry crisp, filling steaming hot, no greasy patches. Drain on a steel rack.",
        "Serve hot with imli chutney. Hold 20 minutes in a low oven on a rack, not stacked. Label gluten and frying oil.",
    ],
    "Sarson da saag (no onion garlic)": [
        "Mise en place. Pick through 1 kg mustard greens, 250 g spinach and optional bathua. Wash in several changes of water until grit is gone. Set a heavy stainless steel kadhai — never aluminium.",
        "Chop greens roughly. Slice ginger and green chilli. Keep 3 tbsp makki atta ready for thickening.",
        "Put greens, ginger, chilli and salt in the kadhai with a splash of water. Cover. Cook on medium-low 35–45 minutes until the mustard is fully soft and the smell of raw saag is gone.",
        "Mash with a wooden mathani or a potato masher to a coarse puree — not a blender slurry unless you prefer it smooth. Leave some fibre.",
        "Sprinkle makki atta. Stir 8–10 minutes on low so the flour cooks out and the saag thickens to a slow ribbon. Add a little hot water if it catches.",
        "In a small steel tadka pan heat ghee. Bloom 1/2 tsp hing, remaining ginger and chilli 20–30 seconds. Pour over the saag. Stir.",
        "Doneness: saag is silky, no raw maize-flour taste, mustard heat present but not bitter. Rest 3 minutes off the heat.",
        "Serve hot with makki di roti and a knob of white butter. Hold above 63 C. Do not store in aluminium. Reheat once only, loosening with hot water.",
    ],
    "Langar-style dal (urad-chana, no onion garlic)": [
        "Mise en place. Wash 1 cup sabut urad and 1/2 cup chana dal. Soak 30 minutes. Set a heavy stainless steel pot — langar dal wants a long, quiet simmer, never aluminium.",
        "Drain. Cover with fresh water by 4 cm. Add turmeric, sliced ginger and salt. Bring to a boil. Skim foam.",
        "Simmer 75–90 minutes, stirring every 10 minutes, until both dals collapse and the liquor is creamy. Add hot water as needed; the dal should look like a thick porridge, not soup.",
        "Mash a third of the pot against the side so the gravy binds. Stir in chopped tomato. Cook 8 minutes until the tomato melts.",
        "Tadka: heat ghee in a steel pan. Bloom cumin and hing 20–30 seconds, then chilli powder off the heat so it does not burn. Pour over the dal. Cover 2 minutes to trap the aroma.",
        "Doneness: urad skins soft, chana creamy, no chalky centre. Salt should taste round, not sharp.",
        "Serve hot in steel bowls, 1 ladle per portion, with roti or rice. Hold like langar: hot, loose, stirred. Cool quickly if storing. Reheat to a full simmer once.",
    ],
    "Chole (Amritsari-ish, no onion garlic)": [
        "Mise en place. Soak 2 cups chickpeas overnight. Drain. Set a steel pressure cooker or heavy pot — never aluminium. Check chole masala for onion or garlic powder.",
        "Cook chickpeas with a teabag or a piece of amla, salt and water until very soft, 25–30 minutes under pressure or 60 minutes open. Drain, reserve 1 cup liquor. Discard the teabag.",
        "Blend 2 tomatoes to a puree. Heat ghee in a steel kadhai. Bloom 1 tsp cumin and 1/2 tsp hing 20–30 seconds.",
        "Add tomato, 2 tsp chole masala, chilli, amchur and salt. Cook 8–10 minutes until the fat separates and the puree looks jammy.",
        "Add chickpeas and reserved liquor. Simmer 15–20 minutes, crushing a few chana against the pan so the gravy thickens. Optional: 1 tsp anardana.",
        "Doneness: gravy coats a spoon, chickpeas creamy inside, colour deep brown-red. Rest 5 minutes.",
        "Serve hot with bhatura or roti. Garnish coriander. Hold hot; the gravy skins if left uncovered. Label legumes.",
    ],
    "Aloo gobhi (no onion garlic)": [
        "Mise en place. Cut 1 cauliflower into even florets. Peel and cube 3 potatoes the same size. Set a stainless steel kadhai — never aluminium.",
        "Rinse cauliflower in salted water 5 minutes. Drain well so it does not steam soggy.",
        "Heat ghee. Bloom cumin and hing 20–30 seconds. Add ginger. Add potato. Toss 3 minutes.",
        "Add cauliflower, turmeric, chilli, coriander and salt. Toss to coat. Cover. Cook on medium-low 12–15 minutes, stirring every 3 minutes, until a knife slips through potato.",
        "Uncover. Raise heat 2–3 minutes to dry the masala so it clings, not pools. Optional chopped tomato in the last 4 minutes.",
        "Doneness: florets tender with light brown edges, potato cooked, spice dry on the vegetable. Finish coriander.",
        "Serve hot as a side. Hold covered 20 minutes. Do not add water at the pass or it goes mushy.",
    ],
    "Baingan bharta (no onion garlic)": [
        "Mise en place. Wipe 3 large brinjals. Set a cast-iron grill or open flame and a steel kadhai — never aluminium.",
        "Prick brinjals. Roast, turning, until the skin is charred and the flesh collapses, 15–20 minutes. Cool slightly. Peel. Mash with a fork — leave some texture.",
        "Heat ghee in the kadhai. Bloom cumin and hing 20–30 seconds. Add ginger and green chilli. Add chopped tomato. Cook 6–8 minutes until jammy.",
        "Add mashed baingan, salt and coriander. Cook 8–10 minutes, stirring, until the bharta looks dry-ish and smells smoky, not raw.",
        "Doneness: no watery pool, smoky aroma, tomato melted. Taste salt and chilli.",
        "Serve hot with roti. Hold covered. The dish improves after 10 minutes rest. Label nightshade if needed.",
    ],
    "Punjabi kadhi pakora (no onion)": [
        "Mise en place. Whisk yogurt and besan for the kadhi until lump-free. Mix a thicker besan batter for pakora with ajwain, chilli and optional spinach. Set a steel kadhai for frying and a heavy pot for simmering — never aluminium.",
        "Heat frying oil to 175 C. Drop spoonfuls of pakora batter. Fry 4–5 minutes until gold and cooked through. Drain on a steel rack.",
        "Thin the yogurt-besan mix with water. Pour into the pot. Add turmeric and salt. Bring to a gentle simmer, stirring so it does not split. Cook 20–25 minutes until the raw besan smell is gone and the kadhi coats a spoon.",
        "Slip in pakora. Simmer 5 minutes so they soak but still hold a centre.",
        "Tadka: ghee, cumin, methi seeds, dry chilli, hing — 20–30 seconds. Pour over. Cover 1 minute.",
        "Doneness: kadhi silky, not chalky; pakora soft-centred. If it splits, whisk off the heat and do not boil hard.",
        "Serve hot with rice. Hold on the lowest heat, stirred. Pakora continue to swell — add a splash of hot water if it thickens too far.",
    ],
    "Makki di roti (maize, no onion)": [
        "Mise en place. Warm 3 cups makki atta with salt. Boil water. Set a cast-iron tawa — not aluminium.",
        "Pour hot water into the atta gradually. Knead with wet hands to a soft, crack-free dough. Work in batches; maize dries fast. Keep unused dough covered with a damp cloth.",
        "Pinch a ball. Flatten between oiled sheets or pat by hand to 15 cm, about 3 mm thick. Repair cracks with wet fingers.",
        "Cook on a medium tawa 1–2 minutes until the face dries. Flip. Cook the second side. Flip again and press gently until brown spots appear. Finish with ghee.",
        "Doneness: no raw maize in the centre, edges set, spots brown not black. Stack in a cloth.",
        "Serve hot with sarson da saag. Hold wrapped 20 minutes. Re-warm 20 seconds on the tawa if they stiffen.",
    ],
    "Tandoori roti (atta, no garlic butter)": [
        "Mise en place. Mix 3 cups atta, salt and water to a soft dough. Rest 15 minutes. Set a clay tandoor or a cast-iron tawa — never garlic butter, never aluminium.",
        "Divide into 8. Roll 3 mm thick. Lightly wet one face if using a tandoor so it sticks to the wall.",
        "Bake in a hot tandoor 60–90 seconds until puffed with charred blisters. On a tawa: cook, then invert over the flame or press to puff.",
        "Brush with plain ghee only.",
        "Doneness: cooked through, light char, no wet dough. Serve immediately.",
        "Hold in a cloth-lined steel box up to 15 minutes. Do not wrap in plastic.",
    ],
    "Missi roti Punjabi (besan, no onion)": [
        "Mise en place. Mix 2 cups atta, 1 cup besan, ajwain, chilli and salt. Add water to a firm dough. Rest 10 minutes. Set a cast-iron tawa.",
        "Roll 3 mm thick. Dust with atta, not extra besan (besan burns).",
        "Cook on medium tawa until brown spots. Flip. Ghee on the cooked face. Flip again 20 seconds.",
        "Doneness: no raw besan taste, spots even. Serve hot with dal or raita.",
        "Hold wrapped 20 minutes. Refresh on the tawa.",
    ],
    "Pinni (atta-ghee-nuts)": [
        "Mise en place. Weigh 2 cups atta, 1 cup ghee, 1 cup powdered sugar or jaggery, almonds and cardamom. Set a heavy steel kadhai — never aluminium.",
        "Melt ghee. Add atta. Roast on low 18–22 minutes, stirring constantly, until the atta is biscuit-brown and smells like toasted wheat. Optional gond: fry in ghee first until it puffs, crush, add at the end.",
        "Cool 8–10 minutes — sugar will melt if the mix is scorching hot. Stir in sugar, crushed cardamom and chopped almonds.",
        "While still warm, press into 40–45 g pinnis. Pack firmly so they do not crumble.",
        "Doneness: roasted aroma, no raw atta, holds shape when cool.",
        "Cool fully. Store in a steel tin. Serve at room temperature. Label gluten, milk (ghee) and tree nuts.",
    ],
    "Gajar ka halwa (no onion)": [
        "Mise en place. Grate 1 kg red carrots. Measure 1 L milk, 3/4 cup sugar, 1/2 cup ghee. Set a heavy stainless steel kadhai — never aluminium (milk and carrot acid).",
        "Cook carrot in the milk on medium, stirring, until the milk is absorbed and the mass is dry, 30–40 minutes.",
        "Add ghee. Roast 8–10 minutes until the carrot shines and the raw smell is gone.",
        "Add sugar. It will loosen. Cook until it leaves the sides of the pan, 8–12 minutes. Finish cardamom and nuts.",
        "Doneness: glossy, spoon leaves a trail, no watery milk. Rest 5 minutes.",
        "Serve hot or warm. Hold in a bain of hot water. Label milk and tree nuts.",
    ],
    "Atta gur pinni winter (jaggery)": [
        "Mise en place. Weigh 2 cups atta, 1 cup ghee, 1 cup grated jaggery, sesame and a pinch of dry ginger. Steel kadhai — never aluminium.",
        "Roast atta in ghee on low 18–22 minutes to biscuit-brown.",
        "Cool 5 minutes. Mix jaggery, sesame and ginger. Jaggery should melt from residual heat, not from a blast of flame (it burns).",
        "Shape pinnis while warm. Cool to set.",
        "Doneness: holds shape, no raw atta, jaggery mixed through.",
        "Store airtight. Serve at room temperature. Label gluten and sesame.",
    ],
    "Phirni (Punjabi rice pudding)": [
        "Mise en place. Soak 1/2 cup rice 30 minutes. Grind to a wet paste. Measure 1 L milk, sugar, saffron, cardamom. Heavy stainless steel milk pot and clay bowls — never aluminium.",
        "Bring milk to a simmer. Stir in rice paste. Cook on low 20–25 minutes, stirring, until the phirni is thick and the rice is cooked, no grit.",
        "Add sugar, saffron soaked in 1 tbsp warm milk, and cardamom. Cook 5 minutes more. It thickens further as it cools.",
        "Pour into clay bowls. Cool. Chill at least 2 hours.",
        "Doneness: sets to a soft quiver, grains fine, saffron aroma. No skin if you press cling on the surface.",
        "Serve chilled. Hold refrigerated up to 24 hours. Label milk.",
    ],
    "Kheer (rice, no onion)": [
        "Mise en place. Wash 1/2 cup basmati. Measure 1.5 L milk, sugar, cardamom, raisins, almonds. Heavy stainless steel milk pot — never aluminium.",
        "Simmer rice in milk on low 35–45 minutes, stirring often so it does not catch. The kheer should look creamy and the rice should bloom.",
        "Add sugar, cardamom, raisins and almonds. Cook 5 minutes. Sugar thins it; reduce 3 minutes more if needed.",
        "Doneness: coats a spoon, rice tender, not porridge-glue. Rest 5 minutes.",
        "Serve hot or chilled. Hold accordingly. Label milk and tree nuts.",
    ],
    "Lassi (sweet, no onion)": [
        "Mise en place. Chill 2 cups dahi, steel glasses and ice. Measure sugar, cardamom, optional malai. No onion, no savoury tadka.",
        "Whisk or blend dahi with chilled water or milk, sugar and cardamom until frothy, 20–30 seconds. Do not over-blend or it goes thin and sour-tasting.",
        "Taste sweetness. Adjust. Add ice to the glass, not the blender, if you want it to stay thick.",
        "Doneness: pourable foam, no dahi lumps, cold through.",
        "Serve immediately in a steel glass. Optional malai on top. Hold chilled up to 1 hour; stir before service. Label milk.",
    ],
    "Mooli salad (white radish, no onion)": [
        "Mise en place. Peel 2 white radishes and 1 carrot. Set a steel or glass bowl. No onion.",
        "Grate. Squeeze firmly in a cloth to remove water or the salad weeps on the pass.",
        "Toss with lemon, slit green chilli, salt, coriander and roasted cumin. Taste. It should be sharp and clean.",
        "Doneness: crisp, not wet; seasoning bright.",
        "Serve cold at once. Hold 30 minutes covered and chilled. Drain if liquid collects. Label mustard if radish is an issue for the guest.",
    ],
    "Kheera raita (cucumber, no onion)": [
        "Mise en place. Whisk 2 cups dahi until smooth. Grate 1 cucumber. Set a steel or glass bowl. No onion.",
        "Squeeze cucumber dry. Fold into dahi with roasted cumin, salt and chopped mint.",
        "Chill 20 minutes so the flavours settle. Stir. Taste salt — cold dulls it slightly, so season a touch higher than you think.",
        "Doneness: thick enough to mound, cucumber crisp, no water pooling.",
        "Serve cold. Hold chilled up to 2 hours. Stir at the pass. Label milk.",
    ],
    "Chana salad (boiled chickpea, no onion)": [
        "Mise en place. Drain 2 cups boiled chickpeas well. Dice tomato and cucumber even and small. Steel or glass bowl. No onion.",
        "Toss chickpeas with tomato, cucumber, lemon, chilli, cumin, salt and coriander. The lemon should coat, not puddle.",
        "Rest 5 minutes. Toss again. Taste.",
        "Doneness: chickpeas intact, vegetables crisp, seasoning even.",
        "Serve cold. Hold 1 hour chilled. Do not add onion at the pass. Label legumes.",
    ],
    "Samosa (nationwide aloo, no onion)": [
        "Mise en place. Prepare a firm maida pastry with ghee and ajwain, and a dry potato-pea filling with cumin, hing and amchur. Steel kadhai for frying — never aluminium. Confirm no onion in the filling.",
        "Rest dough 20 minutes. Cool the filling completely or the pastry splits.",
        "Form cones, fill 2 tbsp, seal with water. No gaps.",
        "Fry at 170–175 C in batches until deep gold, 8–10 minutes. Drain on a steel rack.",
        "Doneness: blistered pastry, steaming filling, not greasy.",
        "Serve hot with imli chutney. Label gluten. Hold 20 minutes on a rack.",
    ],
    "Pakora mixed veg (no onion)": [
        "Mise en place. Slice potato, spinach and chilli; cube paneer. Whisk a thick besan batter with ajwain, hing, chilli and salt. Steel kadhai — never aluminium. No onion rings.",
        "Heat oil to 175–180 C. Dip pieces so they are coated, not drowning. Fry in batches 3–5 minutes until the crust is gold and the vegetable is tender.",
        "Do not crowd — temperature drop makes soggy pakora. Drain on a steel rack, not a heap of paper in the bowl.",
        "Doneness: crisp shell, no raw besan, paneer hot. Serve at once with chutney.",
        "Hold 10 minutes only. Label gluten (besan is usually chickpea; still check hing) and milk if paneer is in the mix.",
    ],
    "Idli sambar plate (South + national, no onion garlic sambar)": [
        "Mise en place. Idli batter ready. For sambar: toor dal, pumpkin, drumstick, tomato, tamarind, sambar powder with no onion or garlic, mustard, hing, curry leaf. Stainless steel steamer and kadhai — never aluminium.",
        "Steam idlis in a greased steel mould 10–12 minutes until a wet finger does not stick. Rest 1 minute before unmoulding.",
        "Cook dal and vegetables until soft. Add tamarind and sambar powder. Simmer 8 minutes.",
        "Tadka: mustard, hing, curry leaf in ghee 20–30 seconds. Pour over. No onion, no garlic, no sambar onion paste.",
        "Coconut chutney: coconut, ginger, chilli, salt, tempered mustard — no onion.",
        "Doneness: idli spongy; sambar coats a spoon, not watery. Serve hot, 3 idlis per portion with a ladle of sambar.",
        "Hold idlis in a covered steamer off the boil. Hold sambar hot. Label coconut and possible gluten in hing.",
    ],
    "Dal tadka (yellow dal, no onion garlic)": [
        "Mise en place. Wash 1.5 cups toor dal. Set a steel pot and a tadka pan — never aluminium. No fried onion.",
        "Cook dal with turmeric and water until completely soft, 20–25 minutes. Mash lightly. Add chopped tomato and salt. Simmer 5 minutes.",
        "Tadka: ghee, cumin, hing, dry chilli — bloom 20–30 seconds until fragrant. Pour over the dal. Cover 1 minute.",
        "Finish coriander. Consistency should be pourable, not paste.",
        "Doneness: no whole grains of dal, tadka aroma on top. Serve hot with rice or roti.",
        "Hold hot, stirred. Loosen with hot water as it sits. Label possible gluten in hing.",
    ],
    "Palak paneer (no onion garlic)": [
        "Mise en place. Wash 500 g spinach. Cube 300 g paneer. Set a steel pot and kadhai — never aluminium. No onion paste.",
        "Blanch spinach 45–60 seconds. Shock. Squeeze dry. Puree with ginger and green chilli, leaving a little texture.",
        "Heat ghee. Bloom cumin and hing 20–30 seconds. Cook chopped tomato 5–6 minutes. Add puree. Simmer 6–8 minutes until the raw spinach smell goes.",
        "Add paneer, garam masala, salt and optional cream. Simmer 3 minutes only — longer and the paneer toughens.",
        "Doneness: gravy coats paneer, colour deep green, no watery pool. Serve hot.",
        "Hold hot up to 20 minutes. Label milk. Do not reboil hard.",
    ],
    "Chana masala (no onion garlic)": [
        "Mise en place. Soak and cook 2 cups chickpeas until soft. Steel kadhai — never aluminium. Check masala packets for onion or garlic powder.",
        "Heat ghee. Bloom cumin and hing. Cook tomato with coriander, chilli, amchur, garam masala and salt until fat separates.",
        "Add chickpeas and a ladle of cooking liquor. Simmer 12–15 minutes, crushing a few chana for body.",
        "Doneness: gravy thick, chickpeas creamy. Serve hot with roti or rice.",
        "Hold hot. Label legumes.",
    ],
    "Aloo gobi (national dry, no onion)": [
        "Mise en place. Even florets and potato cubes. Steel kadhai — never aluminium.",
        "Bloom cumin and hing in ghee. Add vegetables, turmeric, chilli, coriander and salt. Cover-cook 12–15 minutes, stirring.",
        "Uncover and dry the masala 2–3 minutes so it clings.",
        "Doneness: tender with dry spice coat, not mush. Serve hot as a side.",
        "Hold covered 20 minutes.",
    ],
    "Bhindi masala (no onion garlic)": [
        "Mise en place. Wipe 500 g okra dry — water makes slime. Cut 3 cm pieces. Steel kadhai — never aluminium.",
        "Fry okra in oil on medium-high 6–8 minutes until the slime cooks off and edges colour. Lift out.",
        "In the same pan bloom cumin and hing. Cook tomato, chilli, coriander, amchur and salt 4 minutes. Return okra. Toss 3 minutes.",
        "Doneness: okra tender not mushy, masala dry on the pieces. Serve hot.",
        "Hold uncovered a few minutes so steam does not return the slime.",
    ],
    "Jeera aloo (no onion)": [
        "Mise en place. Boil 4 potatoes until just tender. Cool slightly. Cube. Steel kadhai — never aluminium.",
        "Heat ghee. Bloom cumin and hing until the cumin darkens a shade, 20–30 seconds. Add chilli.",
        "Toss potatoes with amchur, coriander and salt 3–4 minutes until edges take colour.",
        "Doneness: potatoes hot, cumin fragrant, dry. Serve immediately.",
        "Hold 15 minutes covered. Do not add water.",
    ],
    "Phulka / roti (national)": [
        "Mise en place. Mix atta and water to a soft dough. Rest 10–15 minutes. Cast-iron tawa — not aluminium.",
        "Divide. Roll 2 mm thick, even, round. Dust lightly.",
        "Cook first side 20 seconds until bubbles. Flip. Cook until brown spots. Flip onto the flame or press to puff.",
        "Optional ghee. Stack in a cloth.",
        "Doneness: puffed or fully cooked, no raw patches. Serve hot.",
        "Hold wrapped 20 minutes. Refresh on the tawa.",
    ],
    "Naan (tandoor, no garlic)": [
        "Mise en place. Mix maida, yogurt, baking powder, salt and a little ghee. No garlic, no garlic butter. Rest 30 minutes. Clay tandoor or very hot steel tray.",
        "Divide. Roll teardrops 4 mm thick. Wet the back face if sticking to a tandoor wall.",
        "Bake until puffed with charred blisters, 60–90 seconds. Brush with plain ghee only.",
        "Doneness: cooked through, blistered, soft. Serve at once.",
        "Hold 10 minutes in a cloth. Label gluten and milk.",
    ],
    "Jeera rice (national, no onion)": [
        "Mise en place. Rinse 2 cups basmati until the water runs clearer. Soak 15 minutes. Drain. Steel pot — never aluminium. No fried onion.",
        "Heat ghee. Bloom 1 tsp cumin, 2 bay leaves and 4 cloves 20–30 seconds.",
        "Add rice. Toss 1 minute. Add measured water and salt (about 1.75 cups water per cup rice for this soak). Bring to a boil. Cover. Low heat 12 minutes. Rest 5 minutes. Fluff.",
        "Doneness: grains separate, cumin visible, no wet clump. Serve hot.",
        "Hold covered 20 minutes. Steam only — do not stir hard.",
    ],
    "Gulab jamun (khoya, no onion)": [
        "Mise en place. Mix khoya and a little maida to a smooth dough — no cracks, no extra flour. Sugar syrup with rose and cardamom, one-string, warm. Steel kadhai of ghee — never aluminium.",
        "Shape 16 smooth balls. If they crack, knead with a drop of milk.",
        "Fry on low-medium, 6–8 minutes, turning, until deep brown. High heat colours the outside and leaves a raw centre.",
        "Drain 30 seconds. Soak in warm syrup 30 minutes, turning once.",
        "Doneness: balls swollen, syrup in the centre, no doughy core. Serve warm, 2 per portion.",
        "Hold in syrup. Label milk and gluten.",
    ],
    "Jalebi (fermented batter)": [
        "Mise en place. Fermented maida batter in a piping cloth. One-string saffron sugar syrup, warm. Steel kadhai of ghee — never aluminium.",
        "Pipe tight coils into 170 C fat. Fry until crisp and orange-gold, 1–2 minutes a side.",
        "Dip in syrup 20–30 seconds. Lift. Drain on a steel rack.",
        "Doneness: crisp, syrup in the tunnels, not soggy. Serve hot or at room temperature within 2 hours.",
        "Label gluten. Do not hold in a closed box or they sweat.",
    ],
    "Besan ladoo (national)": [
        "Mise en place. Weigh 2 cups besan, 1 cup ghee, 1 cup powdered sugar, cardamom, nuts. Heavy steel kadhai — never aluminium.",
        "Roast besan in ghee on low 15–20 minutes until the colour is deep gold and the raw smell is gone. Stir without pause.",
        "Cool 10 minutes. Mix sugar, cardamom and nuts. Shape 30 g ladoos while warm.",
        "Doneness: holds shape, no raw besan. Cool fully.",
        "Store in a tin. Label milk and tree nuts. Besan is chickpea — still verify hing is not in this mix.",
    ],
    "Kheer (rice milk, national)": [
        "Mise en place. Rice, milk, sugar, cardamom, nuts. Heavy stainless steel milk pot — never aluminium.",
        "Simmer rice in milk 35–45 minutes, stirring, until creamy.",
        "Add sugar, cardamom and nuts. Cook 5 minutes more.",
        "Doneness: coats a spoon. Serve hot or chilled.",
        "Label milk and tree nuts. Festival bowl — hold to the service temperature you choose.",
    ],
    "Rasmalai (Bengal-to-nation)": [
        "Mise en place. Fresh chhena discs, reduced milk (rabri) with saffron and pistachio. Steel pots — never aluminium.",
        "Poach chhena discs in light sugar syrup 8–10 minutes until they swell. Squeeze gently.",
        "Soak in warm rabri at least 1 hour, chilled after that.",
        "Doneness: discs spongy, milk thick enough to nap, saffron aroma. Serve chilled, 2 discs per portion.",
        "Hold refrigerated. Label milk and tree nuts.",
    ],
    "Fruit custard (party, veg cornstarch)": [
        "Mise en place. Milk, sugar, cornstarch, mixed fruit, cardamom. Steel pot then a glass bowl. No eggs.",
        "Cook milk, sugar and slurried cornstarch on medium, stirring, until it thickens and the raw starch taste is gone, 6–8 minutes. Add cardamom. Cool completely, stirring so a skin does not form.",
        "Fold diced fruit only when the custard is cold — warm custard weeps and the fruit goes dull.",
        "Doneness: spoonable, fruit distinct, no egg. Chill 1 hour.",
        "Serve cold. Hold 4 hours chilled. Label milk. Use fruit that does not brown badly, or toss banana at the last minute.",
    ],
    "Kachumber no onion (national)": [
        "Mise en place. Dice cucumber, tomato and chilli even. Steel or glass bowl. No onion.",
        "Toss with lemon, cumin, coriander and salt just before service.",
        "Doneness: crisp, bright, not watery. Taste salt and lemon.",
        "Serve cold as a side salad.",
        "Hold 20 minutes. Drain if it weeps. Do not add onion at the pass.",
    ],
    "Dahi raita mixed veg (no onion)": [
        "Mise en place. Whisk dahi smooth. Small dice cucumber and boiled potato. No onion.",
        "Fold vegetables with cumin, salt, chilli powder and coriander. Chill 15 minutes. Stir.",
        "Doneness: thick, seasoned, vegetables distinct. Serve cold.",
        "Hold 2 hours chilled. Stir at the pass.",
        "Label milk. Keep onion off this bowl even if the rest of the table has kachumber with onion.",
    ],
    "Sprouts chaat (no onion)": [
        "Mise en place. Drain moong sprouts well. Dice tomato. Have lemon, chilli, cumin, sev, coriander, salt and pomegranate ready. No onion.",
        "Toss sprouts with tomato, lemon, chilli, cumin and salt. Fold sev and pomegranate at the last minute so sev stays crisp.",
        "Doneness: tangy, crunchy, not wet. Serve immediately.",
        "Hold 15 minutes only or the sev softens.",
        "Street-style sattvic. Label legumes and possible gluten in sev.",
    ],
}
